
# -------------------------- #
#         Phony Rules        #
# -------------------------- #

.PHONY: all clean fclean re format tidy

# -------------------------- #
#      Makefile Setting      #
# -------------------------- #

SHELL =	/bin/bash
RM = rm -f

# -------------------------- #
# 　　　　　　Target　　　      #
# -------------------------- #

NAME = wordle

# -------------------------- #
# 　　　Compiler Flags        #
# -------------------------- #

CXX			= c++
CXXFLAGS	= -Wall -Werror -Wextra

# -------------------------- #
#          Include           #
# -------------------------- #

INCLUDE_DIR	= include
INCLUDE		= -I $(INCLUDE_DIR)

# -------------------------- #
#     Source Directories     #
# -------------------------- #

SRC_DIRS	=	src

# -------------------------- #
#        Source Files        #
# -------------------------- #


SRCS	=	$(addprefix src/, \
				main.cpp   \
			)

# -------------------------- #
#        VPATH Setup         #
# -------------------------- #

# Dependency generation flags:
# foreach: Iterate over each directory in SRC_DIRS
# eval: Evaluate the string as Makefile syntax during parsing
# vpath %.cpp $(dir): Set search path for .cpp files in the specified directory
# Result: Make will search all SRC_DIRS when looking for .cpp source files
$(foreach dir,$(SRC_DIRS), $(eval vpath %.cpp $(dir)))

# -------------------------- #
#     Object & Dependency    #
# -------------------------- #

# patsubst: Pattern substitution function
OBJ_DIR		=	.obj
OBJS		=	$(patsubst %.cpp, $(OBJ_DIR)/%.o, $(notdir $(SRCS)))
 

# -MT: Set the target name in the dependency file (uses automatic variable $@ for current target)
# -MMD: Generate dependency file (.d) during compilation, excluding system headers
# -MP: Add phony targets for each dependency to avoid errors when header files are deleted
# -MF: Specify the output path for the dependency file ($* is the stem without extension)
DEP_DIR		=	.dep
DEPFLAGS	=	-MT $@ -MMD -MP -MF $(DEP_DIR)/$*.d
DEPS		=	$(patsubst %.cpp, $(DEP_DIR)/%.d, $(notdir $(SRCS)))

# -------------------------- #
#    ANSI Escape Sequence    #
# -------------------------- #

DEF_COLOR	= \033[0;39m
GRAY 		= \033[0;90m
RED 		= \033[0;91m
GREEN 		= \033[0;92m
YELLOW 		= \033[0;93m
BLUE 		= \033[0;94m
MAGENTA 	= \033[0;95m
CYAN 		= \033[0;96m
WHITE 		= \033[0;97m

# -------------------------- #
#        Main Targets        #
# -------------------------- #

all	: $(NAME)

# Link object files to create executable
# $^: All prerequisites (all .o files)
# $@: Target name ($(NAME))
$(NAME): $(OBJS)
	@$(CXX) $(CXXFLAGS) $^ -o $@
	@echo -e "[WORDLE] $(GREEN)Build Complete:$(DEF_COLOR) $@"

# -------------------------- #
#        Build Rules         #
# -------------------------- #

# Pattern rule: compile .cpp to .o with dependency generation
# |: Order-only prerequisites (directories must exist but don't trigger rebuild)
# $<: First prerequisite (the .cpp file)
# $@: Target (the .o file)
$(OBJ_DIR)/%.o: %.cpp | $(OBJ_DIR) $(DEP_DIR)
	@$(CXX) $(CXXFLAGS) $(DEPFLAGS) $(INCLUDE) -c $< -o $@

# Create object directory if it doesn't exist
# -: Ignore errors (no error if directory already exists)
$(OBJ_DIR):
	@-mkdir -p $@

# Create dependency directory if it doesn't exist
$(DEP_DIR):
	@-mkdir -p $@

# -------------------------- #
#    Format / Lint Rules     #
# -------------------------- #

format:
	@echo -e "[WORDLE] $(BLUE)Run clang-format$(DEF_COLOR): *.cpp *.hpp"
	@clang-format -i $(SRCS) $(INCLUDE_DIR)/*.hpp

tidy:
	@echo -e "[WORDLE] $(BLUE)Run clang-tidy$(DEF_COLOR): *.cpp"
	@/usr/bin/clang-tidy-12 $(SRCS) -- $(CXXFLAGS) $(INCLUDE)

# -------------------------- #
#       Cleanup Rules        #
# -------------------------- #

# Remove object and dependency files only
clean:
	@$(RM) $(OBJS) $(DEPS)
	@echo -e "[WORDLE] $(BLUE)Deleted Compiled Files$(DEF_COLOR): *.o *.d"

# Remove everything including executable and directories
fclean:
	@$(RM) $(OBJS) $(DEPS)
	@echo -e "[WORDLE] $(BLUE)Deleted Compiled Files$(DEF_COLOR): *.o *.d"
	@$(RM) -r $(NAME) $(OBJ_DIR) $(DEP_DIR)
	@echo -e "[WORDLE] $(BLUE)Deleted Target File and Object File Dir$(DEF_COLOR): $(NAME) $(OBJ_DIR) $(DEP_DIR)"

# Full rebuild: clean everything and rebuild
re:	fclean all

# -------------------------- #
#  Include Dependency Files  #
# -------------------------- #

# Include all .d files (dependency files generated by -MMD)
# -: Ignore errors if .d files don't exist yet (first build)
-include $(DEPS)
